spring.application.name=fintech-auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fintech_auth_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
